### ISSUE TITLE
Installation is insecure by default

### ISSUE THREAD

**Issue by chriswessels** [easy2stake/thegraph#1]
Exposing services unauthenticated is insecure, and could lead to the system being compromised unless the deployer takes additional actions to secure their system. The deployment defaults should be as secure as they can be.

I'd suggest disabling ingress for the agent, grafana and prometheus, and letting users enable those ingresses with the security configuration that is relevant to their setup.

**Comment by easy2stake** [comment]
Thanks for the fast comment @chriswessels  !!
That can be taken care of. So your suggestion is to only leave enabled the service endpoint and flag the other disabled ingresses with comments for the user ?

**Comment by chriswessels** [comment]
Yes. Then I'd expect the easiest secure way to access those services is with `kubectl port-forward` instead of with an ingress.

**Comment by easy2stake** [comment]
Thanks for the feedback.
We adapted the configuration considering  your inputs.
